---
title: Encounter Vineyard Church
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: messages
  values:
    layout: message
image: "/images/site-logo.png"
author: Encounter Vineyard Church
email: jasonbdaniels@gmail.com
description: Find what you're looking for.
address:
- 115 Main St.
- Newport, Ky 41071
phone: 859-442-8882
admin:
  name: Jason Daniels
  email: jasonbdaniels@gmail.com
baseurl: "/encounter-website"
url: https://jasonbdaniels.github.io
facebook_username: encounter.vineyard
cloud:
  s3:
    audio: https://s3.us-east-2.amazonaws.com/encounter-resources
highlighter: rouge
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-seo-tag
exclude:
- how-to
- Gemfile
- Gemfile.lock
